spring:
  application:
    name: jaru

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

auth:
  google:
    redirect-uri: ${GOOGLE_REDIRECT_URI}
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    token-request-uri: ${TOKEN_REQUEST_URI}
    member-info-request-uri: ${MEMBER_INFO_REQUEST_URI}
jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000
  refresh-token-validity: 1209600000